# Generated by Django 5.0.6 on 2024-07-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_recipe_recipe2_delete_recipee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recipe',
        ),
    ]
